"""empty message

Revision ID: 59871c5de741
Revises: 7f92a0ec7bc0
Create Date: 2023-10-17 13:53:14.324867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59871c5de741'
down_revision = '7f92a0ec7bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module1_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module1_id'], ['module1.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module2')
    # ### end Alembic commands ###
